//
//  ProfileWorker.swift
//  Instafeed
//
//  Created by A1GEISP7 on 07/09/19.
//  Copyright (c) 2019 gulam ali. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class ProfileWorker
{
  func getProfileData(completionHandler: @escaping (_ data: Profiledata?, _ error: errorModel?) -> Void)
  {
    let api = ServerURL.firstpoint + ServerURL.Getprofile
    guard let UserToken = UserDefaults.standard.value(forKey: "SavedToken") as? String else {return}
    let params = ["token":UserToken] as [String:Any]
    networking.MakeRestRequest(Url: api, Param: params) { (result:ProfileDataModel?) in
        if let message = result?.message, message == "success"{
            guard let response = result?.data else {return}
            completionHandler(response, nil)
        }else{
            completionHandler(nil, errorModel(message: "error"))
        }
    }
  }
    
    func updateProfile(profileData:Profiledata! , completionHandler: @escaping (_ data: errorModel?, _ error: errorModel?) -> Void){
        let api = ServerURL.firstpoint + ServerURL.updateProfile
        guard let UserToken = UserDefaults.standard.value(forKey: "SavedToken") as? String else {return}
        let params = ["token":UserToken, "first_name": profileData.first_name!, "middle_name": profileData.middle_name!, "last_name": profileData.last_name!, "username": profileData.username!, "birth_date":profileData.birth_date!, "sex": profileData.sex!, "location_id":"1", "bio": profileData.bio!, "website": profileData.website!, "phone": profileData.phone!, "bank_name": profileData.bank_name!, "bank_ifsc_code": profileData.bank_ifsc_code!, "bank_acc_type": profileData.bank_acc_type!, "bank_acc_no": profileData.bank_acc_no!, "pincode": profileData.pincode!, "address": profileData.address!, "city": profileData.city!, "lat": profileData.lat!, "long": profileData.long!] as [String:Any]
        networking.MakeRestRequest(Url: api, Param: params) { (result:errorModel?) in
            if let message = result?.message, message == "success"{
                
                completionHandler(errorModel(message: "success"), nil)
            }else{
                completionHandler(nil, errorModel(message: "error400"))
            }
        }
    }
    
    func updatePic(profilepic:UIImage , completionHandler: @escaping (_ data: imageUpdationResultModel?, _ error: errorModel?) -> Void){
        let api = ServerURL.firstpoint + ServerURL.updateProfilePic
        guard let UserToken = UserDefaults.standard.value(forKey: "SavedToken") as? String else {return}
        let params = ["token":UserToken]
        
        networking.uploadImagesAndData(Api: api, params: params, imagepost: [profilepic], completion: { (response, error ) in
            
            if let message = response?.message, message == "success"{
                
                completionHandler(imageUpdationResultModel(message: "success", image: profilepic), nil)
            }else{
                completionHandler(nil, errorModel(message: "error"))
            }
            
        })
    }
    
    func deletePic(completionHandler: @escaping (_ data: errorModel?, _ error: errorModel?) -> Void){
        let api = ServerURL.firstpoint + ServerURL.removeProfilePic
        guard let UserToken = UserDefaults.standard.value(forKey: "SavedToken") as? String else {return}
        let params = ["token":UserToken]
        networking.MakeRestRequest(Url: api, Param: params) { (result: errorModel?) in
            if let message = result?.message, message == "success"{
                completionHandler(errorModel(message: "success"), nil)
            }else{
                completionHandler(nil, errorModel(message: "error"))
            }
        }
    }
}

