//
//  ProfilePresenter.swift
//  Instafeed
//
//  Created by A1GEISP7 on 07/09/19.
//  Copyright (c) 2019 gulam ali. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ProfilePresentationLogic
{
  func presentProfileData(response: Profile.ProfileData.Response)
    func presentUpdationResult(response: Profile.ProfileData.Response)
    func presentProfilePicUpdation(response: Profile.ProfileData.Response)
    func presentRemovedPicResult(response: Profile.ProfileData.Response)
}

class ProfilePresenter: ProfilePresentationLogic
{
  weak var viewController: ProfileDisplayLogic?
  
  // MARK: Do something
  
  func presentProfileData(response: Profile.ProfileData.Response)
  {
    var viewModel = Profile.ProfileData.ViewModel()
    viewModel.profileData = setDataOnSuccess(response: response.data, viewModel: viewModel)
    viewModel.data = response.data
    viewController?.displayProfileData(viewModel: viewModel)
  }
    func presentUpdationResult(response: Profile.ProfileData.Response) {
        var viewModel = Profile.ProfileData.ViewModel()
        viewModel.result.message = "Profile successfully updated."
        viewController?.displayProfileUpdationResult(viewModel: viewModel)
    }
    
    func presentProfilePicUpdation(response: Profile.ProfileData.Response) {
        var viewModel = Profile.ProfileData.ViewModel()
        viewModel.updatedProfilePicResult.image = response.profilepicResult.image
        viewModel.updatedProfilePicResult.message = "Profile pic successfully updated."
        viewController?.displayProfilePicUpdationResult(viewModel: viewModel)
    }
    
    func presentRemovedPicResult(response: Profile.ProfileData.Response) {
        var viewModel = Profile.ProfileData.ViewModel()
        viewModel.removePicResult.message = "Profile pic successfully removed."
        viewController?.displayProfilePicRemovalResult(viewModel: viewModel)
    }
    
    func setDataOnSuccess(response:Profiledata, viewModel:Profile.ProfileData.ViewModel) -> ProfileViewModel{
        var data = viewModel.profileData
        data.address = response.address
        data.avatar = response.avatar
        data.email = response.email
        data.address = response.address
        data.first_name = response.first_name
        data.last_name = response.last_name
        data.middle_name = response.middle_name
        data.bank_acc_no = response.bank_acc_no
        data.bank_acc_type = response.bank_acc_type
        data.bank_name = response.bank_name
        data.bank_ifsc_code = response.bank_ifsc_code
        data.phone = response.phone
        data.pincode = response.pincode
        data.city = response.city
        data.birth_date = response.birth_date
        data.sex = response.sex
        data.user_id = response.user_id
        data.username = response.username
        
        return data
    }
}
